### PR TITLE
Add documentation and badges

### PR DESCRIPTION
**Pull request by ruiquelhas**
I would like to be the new maintainer of this module.

### CODE REVIEW

**Comment by hueniverse** [comment]
While at it, how about move the project to the latest style:
- Replace Makefile with package.json scripts
- Remove root index.js
- Change package.json licenses key to new style license
- Change lab settings to current setup including linting and assertion lib hook

**Comment by ruiquelhas** [comment]
:+1:

**Comment by ruiquelhas** [comment]
Bump.

**Comment by hueniverse** [comment]
@ruiquelhas npm username?

**Comment by ruiquelhas** [comment]
Yes.

**Pull request merged**
